### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by HarryChen0506** [YutHelloWorld/calendar#2]
我也是刚学react,看到你的项目觉得不错，也尝试模仿写了一遍，为你点赞！ 有个地方我觉得可以优化一下，就是handlerSelectDate这个函数里面，获取activeDate不需要通过元素的属性里面来绕一圈获取，直接通过传参就可以了，同样的，getClassName定位哪个日期，也不需要找到i下标，直接传参就行了，不过这样的话，就要每个日期的span来绑定事件而不是在tbody上设置代理事件，谢谢

**Comment by YutHelloWorld** [comment]
1. getClassName已优化
2. handleSelectDate，还是采用事件委托更好
3. key值修改成稳定唯一值
